# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PlayGround' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Bitberry
pod "Koyomi"
pod 'RevealingSplashView'
pod 'fluid-slider'
  pod 'FontAwesome.swift'
  pod 'Tabman', '~> 2.6'
  pod 'UIScrollView-InfiniteScroll', '~> 1.1.0'
  pod 'GoogleSignIn'
  #pod 'KMNavigationBarTransition'
  #pod 'RRNavigationBar'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'RealmSwift'
  #pod "QRCode"
  pod 'ObjectMapper', '~> 3.3'
  pod 'IGListKit', '~> 3.0'
  pod 'Hue'
  pod 'FLAnimatedImage', '~> 1.0'
  pod 'CryptoSwift'
  pod 'SwiftyJSON', '~> 4.1.0'
  pod 'Kingfisher'
  pod 'SVProgressHUD'
  pod 'SwiftHEXColors'
  pod 'Material'
  pod 'SnapKit'
  pod 'AlamofireImage', '~> 3.3'
  pod 'XLPagerTabStrip', :git => 'https://github.com/xmartlabs/XLPagerTabStrip', :branch => 'master'
  pod 'APAddressBook/Swift'
  pod 'SwiftyRSA'  
  pod 'Localize-Swift', '~> 2.0'
  pod 'BiometricAuthentication'
  pod 'SwiftRichString'
  pod 'SwiftyTimer'

  source 'https://github.com/CocoaPods/Specs.git'
  pod 'libPhoneNumber-iOS', '~> 0.8'
  pod 'KDDragAndDropCollectionViews', '~> 1.5.1'

  source 'https://github.com/CocoaPods/Specs.git'
  pod 'PhoneNumberKit', '~> 2.1'
  pod 'KeychainAccess'
  pod 'SwiftDate'
  pod 'PINCache'
  pod 'UINavigationItem+Margin'
  pod 'SwiftEventBus', :tag => '3.0.0', :git => 'https://github.com/cesarferreira/SwiftEventBus.git'
  pod 'Toast-Swift', '~> 4.0.0'
  pod 'Firebase/Auth'
  pod 'XCGLogger', '~> 6.0.4'
  pod 'Fabric'
  pod 'Crashlytics', '~>  3.10'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Auth'
  pod 'Firebase/Performance'
  pod 'Firebase/MLVision'
  pod 'Firebase/MLVisionLabelModel'
  pod 'Alamofire', '~> 4.8.2'
  pod 'AlamofireObjectMapper', '~> 5.2.0'
  pod 'MaterialComponents'
  # Pods for PlayGround
  pod 'GoogleMaps'
  pod 'GooglePlaces'
end
